openapi: 3.0.3
info:
  title: Molecule Search API
  version: 0.1.0
paths:
  /molecules/:
    get:
      summary: Search for a molecule
      description: 'Search for a molecule'
      operationId: moleculeSearchID
      parameters:
        - in: query
          name: smiles
          example: CCO
          schema:
            type: string
        - in: query
          name: search_type
          schema:
            type: string
            enum:
            - SUBSTRUCTURE
            - EXACT
            - SIMILARITY
            default: EXACT
        - in: query
          name: similarity_value
          schema:
            type: number
            format: float
            minimum: 0
            maximum: 1
            example: 0.5
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Molecule'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Molecule'
        '404':
          description: Molecule not found
components:
  schemas:
    Molecule:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        molecule:
          type: string
          description: Molecule description as sdf or mol file
        iupac:
          type: string
        smiles:
          type: string
        chebiid:
          type: string
        inchi:
          type: string